### ISSUE TITLE
Streaming capability?

### ISSUE THREAD

**Issue by jbmagination** [jbmagination/Luma3DS#2]
@HIDE810 Question, where’s your fork with 10.0.1 + streaming capability?

**Comment by HIDE810** [comment]
Sorry, I've already deleted my fork. But the original fork still exists.
https://github.com/Byebyesky/Luma3DS-Streaming-Fork

**Comment by jbmagination** [comment]
Do you by any chance still have the code?

**Comment by HIDE810** [comment]
Actually my code is almost the same as the original fork's.
If you want to reimplement it, I suggest using its code.

**Comment by jbmagination** [comment]
Alright thanks :)
