### ISSUE TITLE
compile 

### ISSUE THREAD

**Issue by T0biasCZe** [jbmagination/Luma3DS#5]
Hello, can you please upload already compiled boot.firm to releases tab ? I was unsuccesful conpiling it, So pre-compiled for download would be nice

**Comment by hide0123** [comment]
@jbmagination - Could you compile and release it? I'll leave this issue to you.

**Comment by suprstarrd** [comment]
Yes, absolutely!

**Comment by suprstarrd** [comment]
It's been compiled, and is now being added to the Releases tab [here](https://github.com/jbmagination/Luma3DS/latest). It should be up in about 1-5 minutes, it'll just be titled "10.0.1".

**Comment by suprstarrd** [comment]
@T0biasCZe @HIDE810 It is now up. This will be locked and closed.

**Comment by suprstarrd** [comment]
Alright well that didn't work

**Comment by suprstarrd** [comment]
@vertexmachina Hey, your blue light thing is causing Luma3DS to crash upon startup (see the log I've attached [here](https://github.com/jbmagination/Luma3DS/releases/download/other/crash_dump_00000009.dmp)). I'll parse ASAP

**Comment by suprstarrd** [comment]
[Here it is, parsed.](https://github.com/jbmagination/Luma3DS/releases/download/other/crash_dump_00000009_parsed.txt)

**Comment by vertexmachina** [comment]
Strange. I don't know why it would complain about undefined instructions. The code is just standard C and I didn't use any language features that weren't in use somewhere else in the codebase.

**Comment by suprstarrd** [comment]
Even more odd, when I imported the new PRs, it doesn't even show the exception. It just hangs on a black screen

**Comment by hide0123** [comment]
> @vertexmachina Hey, your blue light thing is causing Luma3DS to crash upon startup (see the log I've attached [here](https://github.com/jbmagination/Luma3DS/releases/download/other/crash_dump_00000009.dmp)). I'll parse ASAP

I tested in the commit https://github.com/jbmagination/Luma3DS/commit/f13cfc1337fa6430b34c2b4af793514d794fbcf5 (vertexmachina's commit) on old3ds & new3ds.

Result:
old3ds - worked
new3ds - not worked

This bug is likely to depends on which system model you use.

**Comment by suprstarrd** [comment]
I just tried the commit with the commit before f13cfc1 (without the plugin loader initiated), and it boots up, so it's something going on with the plugin loader, not the actual blue light filter, oddly enough.

**Comment by suprstarrd** [comment]
@T0biasCZe I presume you’ll just want the blue light filters, correct? The plugin loader shouldn’t be much of a problem?

Also, do you use an Old or New 3DS/2DS?

**Comment by vertexmachina** [comment]
Happy to hear my contribution wasn't causing problems. :)

(For reference, the unit I was testing on is a New 2DS.)

**Comment by T0biasCZe** [comment]
Yes, the filter
I have new 2ds

**Comment by suprstarrd** [comment]
Okay, I will make a .firm file for you with the plugin loader removed upon build, so you can use the filter.

I think the bug has something to do with screen type (IPS vs TN) maybe?

**Comment by vertexmachina** [comment]
@T0biasCZe 

Just a note in regards to the usage of the filter.

You'll need to go into the screen filter settings and set persistence to On and set your desired color temperature, save the settings, and then reboot.

On any fresh boot you have to manually set the color temperature once, or sleep and resume. After that your filter settings will be re-applied on wake.

**Comment by suprstarrd** [comment]
Well we're running into some problems #9

**Comment by suprstarrd** [comment]
@T0biasCZe Here it is. It doesn't have the plugin loader like it normally would, but the blue light filter is setup. [Let us know if anything goes wrong.](https://github.com/jbmagination/Luma3DS/releases/download/other/boot.firm)

**Comment by jbmagination** [comment]
Well, with v10.1.2 now out already, we definitely need an upgrad

**Comment by T0biasCZe** [comment]
> 
> 
> @T0biasCZe
> 
> Just a note in regards to the usage of the filter.
> 
> You'll need to go into the screen filter settings and set persistence to On and set your desired color temperature, save the settings, and then reboot.
> 
> On any fresh boot you have to manually set the color temperature once, or sleep and resume. After that your filter settings will be re-applied on wake.

@vertexmachina Hello, what system do you tested it on ? I tried it, i set the colour, set the persistance to on, and saved and rebooted it, and sometimes, after opening/closing it loads back to menu with the blue filter applied, and sometimes its stucked on black screen
I have new 2ds xl

**Comment by suprstarrd** [comment]
#14 @T0biasCZe @vertexmachina
