### ISSUE TITLE
Rosalina can't be exited without force power off after enabling blue light

### ISSUE THREAD

**Issue by suprstarrd** [jbmagination/Luma3DS#9]
**System model:**
New 3DS

**SysNAND version (+emu/redNAND version if applicable):**
Sys 11.13.0-45U

**Entrypoint (How/what you're using to boot Luma3DS):**
boot9strap via SD

**Luma3DS version:**
https://github.com/jbmagination/Luma3DS/actions/runs/87172715
https://github.com/jbmagination/Luma3DS/commit/03422b7552cd4cb9431285ef510f0afc95a845bc

**Luma3DS configuration/options:**

Screen brightness: (4)

Splash: (Before)

Splash duration: (3)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Enable loading external FIRMs and modules: (X)

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
When loading Rosalina and setting the blue light filter, I cannot exit the menu, however if I don't I can. I am forced to reboot by holding the power button, as using Rosalina to power off does not function, and rebooting hangs the 3DS. This only occurs on the `remove-plgldr` branch, but all commits before commit f13cfc1337fa6430b34c2b4af793514d794fbcf5 function as intended.

**Steps to reproduce:**

(To show that it works normally)

1. Open Rosalina menu

2. Attempt to exit Rosalina

3. Open Rosalina menu

4. Attempt to power off

5. Power on and open Rosalina menu 

6. Attempt to reboot

(The bug)

7. Open Rosalina menu

8. Enable blue light temperature (persistence does not matter)

9. Attempt to exit Rosalina, power off, and reboot in order

10. Observe that it doesn't work

**Dump file:**

Not a crash.

**Comment by suprstarrd** [comment]
@HIDE810 Since you made the branch/commit and @vertexmachina since you made the blue light filter

**Comment by suprstarrd** [comment]
What I'm most confused about is why it works with the plugin loader lines removed but not with the plugin loader itself removed. It's just very strange.

**Comment by hide0123** [comment]
OK. Try the latest commit https://github.com/jbmagination/Luma3DS/commit/b31cc0a48b6262430d90152a119dbd2513127974 in the `remove-plgldr` branch.
(Actually this problem will probably be fixed by the commit https://github.com/jbmagination/Luma3DS/commit/1a424a9a3276f0aaf02e5ca6407d69e443a1efe7 .)

**Comment by suprstarrd** [comment]
It works

**Comment by suprstarrd** [comment]
Well, not really? The whole persistence thing isn’t working

**Comment by hide0123** [comment]
Oh, sorry... I made a mistake.
Try again. https://github.com/jbmagination/Luma3DS/commit/84281987244c95d13b84dcea0e65ac7631a8b5d9

**Comment by suprstarrd** [comment]
Alright, everything's working. Thanks!

Also, no need to apologize :)
